[package]
name = "rustunnel-server"
description = "rustunnel 服务端：控制连接 + 工作连接，TCP 端口转发"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords = ["frp", "proxy", "tunnel", "server", "nat"]
categories = ["network-programming"]

[[bin]]
name = "rustunnel-server"
path = "src/main.rs"

[dependencies]
quinn = { workspace = true }
base64.workspace = true
rustunnel-common = { workspace = true }

anyhow = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

[lib]
name = "rustunnel_server"
path = "src/lib.rs"

[dev-dependencies]
quinn = { workspace = true }
